version: "3.8"

services:

  localstack:
    container_name: localstack
    image: localstack/localstack:1.1.0
    # network_mode: bridge               # using default docker-compose network_mode to expose localstack to other containers
    ports:
      - "4510-4559:4510-4559"  # external service port range
      - "4566:4566"            # LocalStack Edge Proxy
    environment:
      - LOCALSTACK_HOSTNAME=localhost.localstack.cloud  # set this env var to expose localstack to other containers
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3,secretsmanager
      # ---
      - DEBUG=1
      # - DATA_DIR=${DATA_DIR-}
      # - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      # - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      # - HOST_TMP_FOLDER=$PWD/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./volumes/tmp/localstack:/var/lib/localstack"
      - "./volumes/var/run/docker.sock:/var/run/docker.sock"
      - "./aws:/etc/localstack/init/ready.d"
